apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-business-job
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark-app:2025
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/app/business_job.py
  deps:
    jars:
      - local:///opt/spark/jars/hadoop-aws-3.4.1.jar
      - local:///opt/spark/jars/bundle-2.32.7.jar
      - local:///opt/spark/jars/spark-snowflake_2.13-3.1.1.jar
      - local:///opt/spark/jars/snowflake-jdbc-3.13.21.jar
  sparkConf:
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
    spark.hadoop.fs.s3a.access.key: "AKIAW3MEDMWOYEEJWZY5"
    spark.hadoop.fs.s3a.secret.key: "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"
    spark.hadoop.fs.s3a.endpoint: s3.ap-south-1.amazonaws.com
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true"
    spark.jars.ivy: ""
    spark.jars.packages: ""    
  arguments:
  - "5000"
  sparkVersion: 4.0.0
  driver:
    labels:
      version: 4.0.0
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
      - name: business-pvc
        mountPath: /business_log
  executor:
    labels:
      version: 4.0.0
    instances: 2
    cores: 1
    memory: 512m
    securityContext:
      capabilities:
        drop:
        - ALL
      runAsGroup: 185
      runAsUser: 185
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
      - name: business-pvc
        mountPath: /business_log
  volumes:
    - name: business-pvc
      persistentVolumeClaim:
        claimName: business-volume